spring.application.name=CadastroDeNinjas



# Cria a URL de conexão do banco
spring.datasource.url=${DATABASE_URL};DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;

# Define o driver correto para o H2
spring.datasource.driver-class-name=org.h2.Driver

# Define o usuário padrão
spring.datasource.username=${DATABASE_USERNAME}

# Deixa a senha vazia (padrão do H2)
spring.datasource.password=${DATABASE_PASSWORD}

#Configurações do JPA //HIBERNATES
spring.h2.console.enabled=true

# Define o caminho para acessar o console
spring.h2.console.path=/h2-console

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
